{
 "title": "08. Aggregated table analysis",
 "tags": [
  "postgres-ai",
  "tables"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   },
   {
    "name": "schema_name",
    "label": "Schema name",
    "query": {
     "query": "label_values(pgwatch_pg_class_relation_size_bytes,schemaname)"
    }
   },
   { "name": "top_n", "label": "Top N tables", "query": "5,10,15,20,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Detailed table view (aggregated table statistics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "columns": [
        { "selector": "schema", "text": "Schema", "type": "string" },
        { "selector": "table_name", "text": "Table Name", "type": "string" },
        { "selector": "total_size", "text": "Total Size", "type": "number" },
        { "selector": "table_size", "text": "Table Size", "type": "number" },
        { "selector": "index_size", "text": "Index Size", "type": "number" },
        { "selector": "toast_size", "text": "TOAST Size", "type": "number" },
        { "selector": "seq_scan", "text": "Seq Scans", "type": "number" },
        { "selector": "idx_scan", "text": "Idx Scans", "type": "number" },
        { "selector": "n_tup_ins", "text": "Inserts", "type": "number" },
        { "selector": "n_tup_upd", "text": "Updates", "type": "number" },
        { "selector": "n_tup_del", "text": "Deletes", "type": "number" },
        { "selector": "n_tup_hot_upd", "text": "HOT Updates", "type": "number" },
        { "selector": "heap_blks_read", "text": "Heap Blks Read", "type": "number" },
        { "selector": "heap_blks_hit", "text": "Heap Blks Hit", "type": "number" },
        { "selector": "idx_blks_read", "text": "Idx Blks Read", "type": "number" },
        { "selector": "idx_blks_hit", "text": "Idx Blks Hit", "type": "number" }
       ],
       "parser": "backend",
       "source": "url",
       "type": "csv",
       "url": "http://flask-pgss-api:8000/table_info/csv",
       "url_options": {
        "data": "",
        "method": "GET",
        "params": [
         { "key": "db_name", "value": "${db_name}" },
         { "key": "cluster_name", "value": "${cluster_name}" },
         { "key": "node_name", "value": "${node_name}" },
         { "key": "schemaname", "value": "${schema_name}" }
        ]
       }
      }
     ]
    }
   ]
  },
  { "title": "Size stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Top $top_n tables by total size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_class_total_relation_size_bytes{relkind=\"114\", schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by size growth /s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_class_total_relation_size_bytes{relkind=\"114\", schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by heap size (excl. TOAST)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_table_size_detailed_table_main_size_b{schema=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schema}}.{{table_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by heap size growth /s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_table_size_detailed_table_main_size_b{schema=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schema}}.{{table_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by TOAST size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_table_size_detailed_toast_indexes_size_b{schema=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schema}}.{{table_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by TOAST size growth /s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_table_size_detailed_total_toast_size_b{schema=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schema}}.{{table_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by indexes size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_table_size_detailed_table_indexes_size_b\n{schema=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schema}}.{{table_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by indexes size growth /s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_table_size_detailed_table_indexes_size_b{schema=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schema}}.{{table_name}}"
    }
   ]
  },
  { "title": "Activity stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Top $top_n tables by tuple inserts per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_ins{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by tuple deletes per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_del{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by tuple HOT updates per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_hot_upd{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by tuple non-HOT updates per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, sum by(schema, table_name, table_full_name) (irate(pgwatch_table_stats_n_tup_upd{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval]) - irate(pgwatch_table_stats_n_tup_hot_upd{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", schema=~\"$schema_name\"}[$__rate_interval])))",
     "legendFormat": "{{table_full_name}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by sequential reads of live tuples",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_all_tables_seq_tup_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by index fetches of live tuples",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_all_tables_idx_tup_fetch{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  { "title": "IO stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Top $top_n tables by total shared block hits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, \n  irate(pgwatch_pg_statio_all_tables_heap_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_idx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_toast_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_tidx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval])\n) * on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by total shared block hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($top_n, \n  (irate(pgwatch_pg_statio_all_tables_heap_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_idx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_toast_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_tidx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))/(irate(pgwatch_pg_statio_all_tables_heap_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_idx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_toast_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_tidx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + (irate(pgwatch_pg_statio_all_tables_heap_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_idx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_toast_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_tidx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))) \n) ",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by total shared block reads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_tables_heap_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \nirate(pgwatch_pg_statio_all_tables_idx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \nirate(pgwatch_pg_statio_all_tables_toast_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \nirate(pgwatch_pg_statio_all_tables_tidx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval])) * on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by total shared block read ratio",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($top_n, \n  (irate(pgwatch_pg_statio_all_tables_heap_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_idx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_toast_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_tidx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))/(irate(pgwatch_pg_statio_all_tables_heap_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_idx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_toast_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_tidx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + (irate(pgwatch_pg_statio_all_tables_heap_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_idx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_toast_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]) + \n  irate(pgwatch_pg_statio_all_tables_tidx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))) \n) ",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by heap shared block hits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_tables_heap_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))* on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by heap shared block reads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_tables_heap_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by TOAST shared block hits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_tables_toast_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))* on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by TOAST shared block reads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_tables_toast_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by index shared block hits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_tables_idx_blks_hit{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval])) * on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by index shared block reads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_tables_idx_blks_read{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"}[$__rate_interval]))* on() group_left() last_over_time(pgwatch_settings_numeric_value{datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 219 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  },
  { "title": "Estimated bloat stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Top $top_n tables by estimated heap bloat %",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_table_bloat_bloat_pct{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}"
    }
   ]
  },
  {
   "title": "Top $top_n tables by estimated heap bloat size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_table_bloat_bloat_size{schemaname=~\"$schema_name\", datname=~\"$db_name\", cluster=\"$cluster_name\", node_name=\"$node_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}"
    }
   ]
  }
 ]
}