{
 "title": "10. Aggregated index analysis",
 "tags": [
  "postgres-ai",
  "indexes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "top_n", "query": "10, 15, 20, 50, 100" },
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Detailed index view",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "columns": [
        { "selector": "bloat_pct", "text": "", "type": "number" },
        { "selector": "bloat_size", "text": "", "type": "number" },
        { "selector": "fillfactor", "text": "", "type": "number" },
        { "selector": "idxname", "text": "", "type": "string" },
        { "selector": "schemaname", "text": "", "type": "string" },
        { "selector": "tblname", "text": "", "type": "string" },
        { "selector": "real_size_mib", "text": "", "type": "number" },
        { "selector": "is_na", "text": "", "type": "number" }
       ],
       "filterExpression": "is_na<1 && bloat_pct>0",
       "parser": "backend",
       "source": "url",
       "type": "csv",
       "url": "http://flask-pgss-api:8000/btree_bloat/csv",
       "url_options": {
        "data": "",
        "method": "GET",
        "params": [
         { "key": "cluster_name", "value": "$cluster_name" },
         { "key": "node_name", "value": "$node_name" },
         { "key": "db_name", "value": "$db_name" }
        ]
       }
      }
     ]
    }
   ]
  },
  { "title": "Size stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Top $top_n indexes by size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_class_relation_size_bytes{relkind=\"105\", cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"})",
     "legendFormat": "{{schemaname}}.{{relname}}"
    }
   ]
  },
  { "title": "Estimated bloat stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Top $top_n indexes by estimated bloat %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_btree_bloat_bloat_pct{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}.{{idxname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by estimated bloat size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk($top_n, pgwatch_pg_btree_bloat_bloat_size{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"})",
     "legendFormat": "{{schemaname}}.{{tblname}}.{{idxname}}"
    }
   ]
  },
  { "title": "Index usage stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Top $top_n indexes by tuples read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_all_indexes_idx_tup_read{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by tuples fetched",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_stat_all_indexes_idx_tup_fetch{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval]))",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  { "title": "IO stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Top $top_n indexes by block reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_indexes_idx_blks_read{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on() group_left() last_over_time(pgwatch_settings_numeric_value{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Top $top_n indexes by block hits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk($top_n, irate(pgwatch_pg_statio_all_indexes_idx_blks_hit{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on() group_left() last_over_time(pgwatch_settings_numeric_value{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "{{schemaname}}.{{relname}}.{{indexrelname}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 71 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}