{
 "title": "11. Single index analysis",
 "tags": [
  "postgres-ai",
  "indexes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "datname",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   },
   {
    "name": "schema_name",
    "label": "Schema name",
    "query": {
     "query": "label_values(pgwatch_pg_stat_all_indexes_idx_scan{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\"},schemaname)"
    }
   },
   {
    "name": "index_name",
    "label": "Index name",
    "query": {
     "query": "label_values(pgwatch_pg_stat_all_indexes_idx_scan{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", schemaname=\"$schema_name\"},indexrelname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Size stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Index size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pgwatch_pg_class_relation_size_bytes{relkind=\"105\", cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", schemaname=\"$schema_name\", relname=\"$index_name\"}",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "Index usage stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Index scans",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_all_indexes_idx_scan{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", schemaname=\"$schema_name\", indexrelname=\"$index_name\"}[$__rate_interval])",
     "legendFormat": "Scans"
    }
   ]
  },
  {
   "title": "Tuples read and fetched",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_stat_all_indexes_idx_tup_read{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", schemaname=\"$schema_name\", indexrelname=\"$index_name\"}[$__rate_interval])",
     "legendFormat": "Tuples read"
    },
    {
     "expr": "irate(pgwatch_pg_stat_all_indexes_idx_tup_fetch{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", schemaname=\"$schema_name\", indexrelname=\"$index_name\"}[$__rate_interval])",
     "legendFormat": "Tuples fetched"
    }
   ]
  },
  { "title": "IO stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Shared block reads and hits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(pgwatch_pg_statio_all_indexes_idx_blks_read{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", schemaname=\"$schema_name\", indexrelname=\"$index_name\"}[$__rate_interval]) * on() group_left() last_over_time(pgwatch_settings_numeric_value{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(pgwatch_pg_statio_all_indexes_idx_blks_hit{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", schemaname=\"$schema_name\", indexrelname=\"$index_name\"}[$__rate_interval]) * on() group_left() last_over_time(pgwatch_settings_numeric_value{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"$datname\", setting_name=\"block_size\"}[1d])",
     "legendFormat": "Hit"
    }
   ]
  },
  { "title": "Estimated bloat stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Boguk ratio (index size / reltuples)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "pgwatch_pg_class_total_relation_size_bytes{relname=\"$index_name\", schemaname=\"$schema_name\"} / pgwatch_pg_class_reltuples{relname=\"$index_name\", schemaname=\"$schema_name\"}",
     "legendFormat": "Boguk ratio (index size / live tuples), current"
    },
    {
     "expr": "pgwatch_pg_index_pilot_best_ratio{indexrelname=\"$index_name\", schemaname=\"$schema_name\"}",
     "legendFormat": "Boguk ratio (index size / live tuples), baseline"
    },
    {
     "expr": "max by () (\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=~\"$index_name\", datname=~\"$datname\"}[1w]) * 8 or\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=~\"$index_name\", datname=\"*\"}[1w]) * 7 or\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=\"*\", datname=~\"$datname\"}[1w]) * 6 or\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=~\"$index_name\", datname=~\"$datname\"}[1w]) * 5 or\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=\"*\", datname=~\"$datname\"}[1w]) * 4 or\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=\"*\", datname=\"*\"}[1w]) * 3 or\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=~\"$index_name\", datname=\"*\"}[1w]) * 2 or\n  last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=\"*\", datname=\"*\"}[1w]) * 1\n) / \nmax by () (\n  8 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=~\"$index_name\", datname=~\"$datname\"}[1w]) * 0 + 1) or\n  7 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=~\"$index_name\", datname=\"*\"}[1w]) * 0 + 1) or\n  6 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=\"*\", datname=~\"$datname\"}[1w]) * 0 + 1) or\n  5 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=~\"$index_name\", datname=~\"$datname\"}[1w]) * 0 + 1) or\n  4 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=\"*\", datname=~\"$datname\"}[1w]) * 0 + 1) or\n  3 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=~\"$schema_name\", indexrelname=\"*\", datname=\"*\"}[1w]) * 0 + 1) or\n  2 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=~\"$index_name\", datname=\"*\"}[1w]) * 0 + 1) or\n  1 * (last_over_time(pgwatch_pg_index_pilot_config_config_value_normalized{config_key=\"index_rebuild_scale_factor\", schemaname=\"*\", indexrelname=\"*\", datname=\"*\"}[1w]) * 0 + 1)\n)",
     "legendFormat": "index_rebuild_scale_factor"
    }
   ]
  }
 ]
}