{
 "title": "04. Wait event analysis (Active Session History)",
 "tags": [
  "postgres-ai",
  "waits",
  "ash"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   },
   {
    "name": "wait_event_type",
    "label": "Wait event type",
    "query": {
     "query": "label_values(pgwatch_wait_events_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=~\"$db_name\"},wait_event_type)"
    }
   },
   {
    "name": "wait_event",
    "label": "Wait event",
    "query": {
     "query": "label_values(pgwatch_wait_events_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=~\"$db_name\", wait_event_type=~\"$wait_event_type\"},wait_event)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active session history",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_by_label(\n  sum by (wait_event_type) (\n    (\n      sum by (wait_event_type, instance) (\n        sum_over_time(\n          pgwatch_wait_events_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=~\"$db_name\"}[$__interval]\n        )\n      ) default 0\n    )\n    / on (instance) group_left()\n    (\n      sum by (instance) (\n        sum_over_time(up{job=\"pgwatch-prometheus\"}[$__interval])\n      ) > 0\n    )\n  ),\n  \"wait_event_type\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (wait_event_type) (\n  (\n    sum by (wait_event_type, instance) (\n      sum_over_time(\n        pgwatch_wait_events_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"server_process\", wait_event_type!=\"Activity\"}[$__interval]\n      )\n    ) default 0\n  )\n  / on (instance) group_left()\n  (\n    sum by (instance) (\n      sum_over_time(up{job=\"pgwatch-prometheus\"}[$__interval])\n    ) > 0\n  )\n)",
     "legendFormat": "Postgres - {{wait_event_type}}"
    },
    {
     "expr": "sum by (wait_event_type) (\n  (\n    sum by (wait_event_type, instance) (\n      sum_over_time(\n        pgwatch_wait_events_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=\"server_process\", wait_event_type=\"Activity\"}[$__interval]\n      )\n    ) default 0\n  )\n  / on (instance) group_left()\n  (\n    sum by (instance) (\n      sum_over_time(up{job=\"pgwatch-prometheus\"}[$__interval])\n    ) > 0\n  )\n)",
     "legendFormat": "Idle Internal - {{wait_event_type}}"
    }
   ]
  },
  {
   "title": "Active session history by event type",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sort_by_label(\n  sum by (wait_event_type, wait_event) (\n    (\n      sum by (wait_event_type, wait_event, instance) (\n        sum_over_time(\n          pgwatch_wait_events_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=~\"$db_name\", wait_event_type=~\"$wait_event_type\"}[$__interval]\n        )\n      ) default 0\n    )\n    / on (instance) group_left()\n    (\n      sum by (instance) (\n        sum_over_time(up{job=\"pgwatch-prometheus\"}[$__interval])\n      ) > 0\n    )\n  ),\n  \"wait_event_type\"\n)",
     "legendFormat": "{{wait_event_type}} - {{wait_event}}"
    }
   ]
  },
  {
   "title": "Active session history by event type and event",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sort_by_label(\n  sum by (wait_event_type, wait_event, query_id) (\n    (\n      sum by (wait_event_type, wait_event, query_id, instance) (\n        sum_over_time(\n          pgwatch_wait_events_total{cluster=\"$cluster_name\", node_name=\"$node_name\", datname=~\"$db_name\", wait_event_type=~\"$wait_event_type\", wait_event=~\"$wait_event\"}[$__interval]\n        )\n      ) default 0\n    )\n    / on (instance) group_left()\n    (\n      sum by (instance) (\n        sum_over_time(up{job=\"pgwatch-prometheus\"}[$__interval])\n      ) > 0\n    )\n  ),\n  \"wait_event_type\", \"query_id\"\n)",
     "legendFormat": "{{wait_event_type}} - {{wait_event}} - {{query_id}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 63 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}