{
 "title": "02. Query performance analysis (top-N)",
 "tags": [
  "postgres-ai",
  "queries"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "Cluster name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b,cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\"},node_name)"
    }
   },
   {
    "name": "db_name",
    "label": "DB name",
    "query": {
     "query": "label_values(pgwatch_db_size_size_b{cluster=\"$cluster_name\", node_name=\"$node_name\", datname!=\"template1\"},datname)"
    }
   },
   { "name": "top_n", "label": "top_n", "query": "5, 10, 15, 20, 50, 100, 500" },
   {
    "name": "legend_label",
    "label": "Query texts",
    "query": "Smart truncation : displayname_long, Raw texts : displayname_raw_long"
   }
  ]
 },
 "panels": [
  {
   "title": "Detailed table view (pg_stat_statements)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "columns": [
        { "selector": "queryid", "text": "Query ID", "type": "string" },
        { "selector": "query_text", "text": "Query text", "type": "string" },
        { "selector": "duration_seconds", "text": "Duration (seconds)", "type": "number" },
        { "selector": "calls", "text": "Calls", "type": "number" },
        { "selector": "calls_per_sec", "text": "Calls/sec", "type": "number" },
        { "selector": "exec_time", "text": "Exec time (ms)", "type": "number" },
        { "selector": "exec_time_per_sec", "text": "Exec time/sec (ms/s)", "type": "number" },
        { "selector": "exec_time_per_call", "text": "Exec time/call (ms)", "type": "number" },
        { "selector": "plan_time", "text": "Planning time (ms)", "type": "number" },
        { "selector": "plan_time_per_sec", "text": "Planning time/sec (ms/s)", "type": "number" },
        { "selector": "plan_time_per_call", "text": "Planning time/call (ms)", "type": "number" },
        { "selector": "rows", "text": "Rows", "type": "number" },
        { "selector": "rows_per_sec", "text": "Rows/sec", "type": "number" },
        { "selector": "rows_per_call", "text": "Rows/call", "type": "number" },
        { "selector": "shared_blks_hit", "text": "Shared blocks hit", "type": "number" },
        { "selector": "shared_blks_hit_per_sec", "text": "Shared blocks hit/sec", "type": "number" },
        { "selector": "shared_blks_hit_per_call", "text": "Shared blocks hit/call", "type": "number" },
        { "selector": "shared_blks_read", "text": "Shared blocks read", "type": "number" },
        { "selector": "shared_blks_read_per_sec", "text": "Shared blocks read/sec", "type": "number" },
        { "selector": "shared_blks_read_per_call", "text": "Shared blocks read/call", "type": "number" },
        { "selector": "shared_blks_dirtied", "text": "Shared blocks dirtied", "type": "number" },
        { "selector": "shared_blks_dirtied_per_sec", "text": "Shared blocks dirtied/sec", "type": "number" },
        { "selector": "shared_blks_dirtied_per_call", "text": "Shared blocks dirtied/call", "type": "number" },
        { "selector": "shared_blks_written", "text": "Shared blocks written", "type": "number" },
        { "selector": "shared_blks_written_per_sec", "text": "Shared blocks written/sec", "type": "number" },
        { "selector": "shared_blks_written_per_call", "text": "Shared blocks written/call", "type": "number" },
        { "selector": "blk_read_time", "text": "Block read time (ms)", "type": "number" },
        { "selector": "blk_read_time_per_sec", "text": "Block read time/sec (ms)", "type": "number" },
        { "selector": "blk_read_time_per_call", "text": "Block read time/call (ms)", "type": "number" },
        { "selector": "blk_write_time", "text": "Block write time (ms)", "type": "number" },
        { "selector": "blk_write_time_per_sec", "text": "Block write time/sec (ms)", "type": "number" },
        { "selector": "blk_write_time_per_call", "text": "Block write time/call (ms)", "type": "number" }
       ],
       "parser": "backend",
       "source": "url",
       "type": "csv",
       "url": "http://flask-pgss-api:8000/pgss_metrics/csv",
       "url_options": {
        "data": "",
        "method": "GET",
        "params": [
         { "key": "time_start", "value": "${__from:date}" },
         { "key": "time_end", "value": "${__to:date}" },
         { "key": "db_name", "value": "${db_name}" },
         { "key": "truncation_mode", "value": "${legend_label}" }
        ]
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Top $top_n queries analysis (pg_stat_statements)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Top $top_n statements by calls per second (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "calls/s" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by execution time per second (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_exec_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_exec_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by execution time per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_exec_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_exec_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by planning time per second (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms/s" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_plan_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_plan_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by planning time per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_plan_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_plan_time_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by rows per second (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_rows{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_rows{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by rows per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_rows{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_rows{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_hit per second (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_hit (in bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_hit_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_read per second (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_read_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_read_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_read (in bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_read_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_read_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_written per second (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_written_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_written_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_written (in bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_written_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_written_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_dirtied per second (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_dirtied_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_dirtied_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by shared_blks_dirtied (in bytes) per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_dirtied_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_shared_bytes_dirtied_total{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL bytes per second (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_wal_bytes{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_wal_bytes{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL bytes per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_wal_bytes{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_wal_bytes{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL fpi per second (in bytes) (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_wal_fpi{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_wal_fpi{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by WAL fpi per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_wal_fpi{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_wal_fpi{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes read per second (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes read per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_read{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes written per second (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "title": "Top $top_n statements by temp bytes written per call (pg_stat_statements)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) * on(queryid) group_left(displayname, displayname_medium, displayname_long, displayname_raw_short, displayname_raw_medium, displayname_raw_long, displayname_full, displayname_queryid) pgwatch_query_info) or (topk($top_n, irate(pgwatch_pg_stat_statements_temp_bytes_written{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])/irate(pgwatch_pg_stat_statements_calls{cluster='$cluster_name', node_name='$node_name', datname=~\"$db_name\"}[$__rate_interval])) unless on(queryid) pgwatch_query_info)",
     "legendFormat": "{{$legend_label}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 102 },
   "options": {
    "content": "<h1>\n  Brought to you by <a href=\"https://postgres.ai\">PostgresAI</a>\n  <img src=\"https://postgres.ai/img/logo.svg\" alt=\"Postgres.AI\" style=\"height: 2em; vertical-align: middle; margin-left: 0.3em;\">\n</h1>\n"
   }
  }
 ]
}