{
 "title": "Self-monitoring dashboard",
 "tags": [
  "postgres-ai",
  "self-monitoring",
  "monitoring-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://flask-pgss-api:8000/version",
     "url_options": { "method": "GET" }
    }
   ]
  },
  {
   "title": "Active monitoring services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"self-cadvisor|self-node-exporter|self-postgres-exporter|victoriametrics|pgwatch-prometheus\"})"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})"
    }
   ]
  },
  {
   "title": "Application memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Victoria Metrics storage size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"victoriametrics\"})"
    }
   ]
  },
  {
   "title": "Victoria Metrics time series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"victoriametrics\"})"
    }
   ]
  },
  { "title": "Host stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "System CPU usage breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"user\"}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"system\"}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"nice\"}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"irq\"}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"softirq\"}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode=\"steal\"}[5m]))",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "System memory usage breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_SReclaimable_bytes",
     "legendFormat": "Application"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    {
     "expr": "node_memory_Cached_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "Cache"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "System network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo|veth.*\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo|veth.*\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "System disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} - node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"}) / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"} * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  { "title": "Disk I/O metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Disk I/O operations (IOPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Disk I/O throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{device!~\"dm-.*\"}[5m]) / rate(node_disk_reads_completed_total{device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{device!~\"dm-.*\"}[5m]) / rate(node_disk_writes_completed_total{device!~\"dm-.*\"}[5m])",
     "legendFormat": "{{device}} write"
    }
   ]
  },
  { "title": "Container resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\".+\"}[5m])",
     "legendFormat": "{{name}} rx"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\".+\"}[5m])",
     "legendFormat": "{{name}} tx"
    }
   ]
  },
  {
   "title": "Container disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{name=~\".+\"}[5m])",
     "legendFormat": "{{name}} read"
    },
    {
     "expr": "rate(container_fs_writes_bytes_total{name=~\".+\"}[5m])",
     "legendFormat": "{{name}} write"
    }
   ]
  },
  { "title": "Victoria Metrics metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Victoria Metrics ingestion rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "samplesps" } },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=\"victoriametrics\"}[5m]))",
     "legendFormat": "Rows inserted"
    }
   ]
  },
  {
   "title": "Scrape duration by target",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(scrape_duration_seconds{job=~\"self-cadvisor|self-node-exporter|self-postgres-exporter|pgwatch-prometheus\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Victoria Metrics storage size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"victoriametrics\"})",
     "legendFormat": "Data size"
    },
    {
     "expr": "sum(vm_cache_size_bytes{job=\"victoriametrics\"})",
     "legendFormat": "Cache size"
    }
   ]
  },
  {
   "title": "Victoria Metrics rows count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_rows{job=\"victoriametrics\"})",
     "legendFormat": "Total rows"
    },
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=\"victoriametrics\"}[5m]))",
     "legendFormat": "Rows inserted rate"
    }
   ]
  },
  { "title": "Sink Postgres database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Sink Postgres connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"measurements\"}",
     "legendFormat": "Active connections"
    },
    { "expr": "pg_settings_max_connections", "legendFormat": "Max connections" }
   ]
  },
  {
   "title": "Sink Postgres transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"measurements\"}[5m])",
     "legendFormat": "Commits"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"measurements\"}[5m])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Sink Postgres database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"measurements\"}",
     "legendFormat": "Database size"
    }
   ]
  },
  {
   "title": "Sink Postgres block I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"measurements\"}[5m]) * 8192",
     "legendFormat": "Disk reads"
    },
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"measurements\"}[5m]) * 8192",
     "legendFormat": "Cache hits"
    }
   ]
  }
 ]
}