{{- if .Values.reporter.enabled }}
{{- $root := . }}
{{- $seenCombinations := dict }}
{{- $combinations := list }}
{{- range $db := .Values.monitoredDatabases }}
  {{- $clusterName := "" }}
  {{- $nodeName := "" }}
  {{- if $db.clusterName }}
    {{- $clusterName = $db.clusterName }}
  {{- else if $root.Values.reporter.clusterName }}
    {{- $clusterName = $root.Values.reporter.clusterName }}
  {{- else if $root.Values.global.clusterName }}
    {{- $clusterName = $root.Values.global.clusterName }}
  {{- else }}
    {{- $clusterName = "k8s-cluster" }}
  {{- end }}
  {{- if $db.nodeName }}
    {{- $nodeName = $db.nodeName }}
  {{- else if $root.Values.reporter.nodeName }}
    {{- $nodeName = $root.Values.reporter.nodeName }}
  {{- else if $root.Values.global.nodeName }}
    {{- $nodeName = $root.Values.global.nodeName }}
  {{- end }}
  {{- $key := printf "%s|%s" $clusterName $nodeName }}
  {{- if not (hasKey $seenCombinations $key) }}
    {{- $_ := set $seenCombinations $key true }}
    {{- $combinations = append $combinations (dict "cluster" $clusterName "nodeName" $nodeName) }}
  {{- end }}
{{- end }}
{{- if and (eq (len $combinations) 0) (or $root.Values.reporter.clusterName $root.Values.global.clusterName) }}
  {{- $clusterName := "" }}
  {{- $nodeName := "" }}
  {{- if $root.Values.reporter.clusterName }}
    {{- $clusterName = $root.Values.reporter.clusterName }}
  {{- else if $root.Values.global.clusterName }}
    {{- $clusterName = $root.Values.global.clusterName }}
  {{- else }}
    {{- $clusterName = "k8s-cluster" }}
  {{- end }}
  {{- if $root.Values.reporter.nodeName }}
    {{- $nodeName = $root.Values.reporter.nodeName }}
  {{- else if $root.Values.global.nodeName }}
    {{- $nodeName = $root.Values.global.nodeName }}
  {{- end }}
  {{- $combinations = append $combinations (dict "cluster" $clusterName "nodeName" $nodeName) }}
{{- end }}
{{- range $idx, $combo := $combinations }}
{{- $clusterName := $combo.cluster }}
{{- $nodeName := $combo.nodeName }}
{{- $suffix := "" }}
{{- if gt (len $combinations) 1 }}
  {{- $safeCluster := $clusterName | replace "_" "-" | replace "." "-" | lower | trunc 20 }}
  {{- $safeNode := $nodeName | replace "_" "-" | replace "." "-" | lower | trunc 10 }}
  {{- if $safeNode }}
    {{- $suffix = printf "-%s-%s" $safeCluster $safeNode }}
  {{- else }}
    {{- $suffix = printf "-%s" $safeCluster }}
  {{- end }}
{{- end }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "postgres-ai-monitoring.fullname" $root }}-reporter{{ $suffix }}
  namespace: {{ include "postgres-ai-monitoring.namespace" $root }}
  labels:
    {{- include "postgres-ai-monitoring.labels" $root | nindent 4 }}
    app.kubernetes.io/component: reporter
    {{- if gt (len $combinations) 1 }}
    postgres.ai/cluster: {{ $clusterName | quote }}
    {{- if $nodeName }}
    postgres.ai/node: {{ $nodeName | quote }}
    {{- end }}
    {{- end }}
spec:
  schedule: {{ $root.Values.reporter.schedule | quote }}
  successfulJobsHistoryLimit: {{ $root.Values.reporter.successfulJobsHistoryLimit | default 3 }}
  failedJobsHistoryLimit: {{ $root.Values.reporter.failedJobsHistoryLimit | default 3 }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "postgres-ai-monitoring.selectorLabels" $root | nindent 12 }}
            app.kubernetes.io/component: reporter
            {{- if gt (len $combinations) 1 }}
            postgres.ai/cluster: {{ $clusterName | quote }}
            {{- if $nodeName }}
            postgres.ai/node: {{ $nodeName | quote }}
            {{- end }}
            {{- end }}
        spec:
          {{- with $root.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-victoriametrics
              image: busybox:1.36
              command: ['sh', '-c', 'until nc -z {{ include "postgres-ai-monitoring.fullname" $root }}-victoriametrics {{ $root.Values.victoriaMetrics.service.port }}; do echo waiting for victoriametrics; sleep 2; done']
          containers:
            - name: reporter
              image: {{ $root.Values.reporter.image }}
              imagePullPolicy: {{ $root.Values.reporter.imagePullPolicy | default "IfNotPresent" }}
              command:
                - /bin/sh
                - -c
                - |
                  set -eu
                  if [ -n "${API_KEY:-}" ]; then
                    exec python postgres_reports.py \
                      --prometheus-url "$PROMETHEUS_URL" \
                      --postgres-sink-url "postgresql://{{ $root.Values.sinkPostgres.user }}:${POSTGRES_PASSWORD}@{{ include "postgres-ai-monitoring.fullname" $root }}-sink-postgres:5432/{{ $root.Values.sinkPostgres.database }}" \
                      --cluster "$CLUSTER" \
                      --node-name "$NODE_NAME" \
                      --output /app/reports/report.json \
                      --api-url "{{ $root.Values.reporter.apiUrl | default "https://postgres.ai/api/general" }}" \
                      --project "{{ $root.Values.reporter.project | default "postgres-ai-monitoring" }}" \
                      --token "$API_KEY"
                  else
                    exec python postgres_reports.py \
                      --prometheus-url "$PROMETHEUS_URL" \
                      --postgres-sink-url "postgresql://{{ $root.Values.sinkPostgres.user }}:${POSTGRES_PASSWORD}@{{ include "postgres-ai-monitoring.fullname" $root }}-sink-postgres:5432/{{ $root.Values.sinkPostgres.database }}" \
                      --cluster "$CLUSTER" \
                      --node-name "$NODE_NAME" \
                      --output /app/reports/report.json \
                      --no-upload
                  fi
              env:
                - name: PROMETHEUS_URL
                  value: "http://{{ include "postgres-ai-monitoring.fullname" $root }}-victoriametrics:{{ $root.Values.victoriaMetrics.service.port }}"
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgres-ai-monitoring.secretName" $root }}
                      key: postgres-password
                - name: CLUSTER
                  value: {{ $clusterName | default "k8s-cluster" | quote }}
                - name: NODE_NAME
{{- if $nodeName }}
                  value: {{ $nodeName | quote }}
{{- else }}
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
{{- end }}
                {{- if $root.Values.secrets.pgwatchConfig }}
                - name: API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgres-ai-monitoring.secretName" $root }}
                      key: pgai-api-key
                      optional: true
                {{- end }}
                
                {{- if $root.Values.victoriaMetrics.auth.enabled }}
                - name: VM_AUTH_USERNAME
                  value: {{ $root.Values.victoriaMetrics.auth.username | quote }}
                - name: VM_AUTH_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "postgres-ai-monitoring.secretName" $root }}
                      key: vm-auth-password
                {{- end }}
                {{- range $key, $value := $root.Values.reporter.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
              {{- with $root.Values.reporter.resources }}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                - name: reports
                  mountPath: /app/reports
          volumes:
            - name: reports
              emptyDir: {}
{{- end }}
{{- end }}
