{{- $createFromValues := .Values.secrets.createFromValues | default false }}
{{- $existingSecretName := "" }}
{{- if .Values.existingSecret }}
  {{- $existingSecretName = .Values.existingSecret.name | default "" }}
{{- end }}
{{- if and $createFromValues (or (not $existingSecretName) (eq $existingSecretName "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-ai-monitoring.secretName" . }}
  namespace: {{ include "postgres-ai-monitoring.namespace" . }}
  labels:
    {{- include "postgres-ai-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgres.password | quote }}
  grafana-admin-user: {{ .Values.secrets.grafana.adminUser | quote }}
  grafana-admin-password: {{ .Values.secrets.grafana.adminPassword | quote }}
  {{- if .Values.secrets.vmAuth }}
  vm-auth-password: {{ .Values.secrets.vmAuth.password | default "" | quote }}
  {{- end }}
  {{- if .Values.secrets.pgwatchConfig }}
  pgai-api-key: {{ .Values.secrets.pgwatchConfig.apiKey | default "" | quote }}
  {{- end }}
  {{- if .Values.secrets.monitoredDatabases }}
  {{- range $key, $value := .Values.secrets.monitoredDatabases }}
  db-password-{{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}

